--CREATING BOOK TABLE
create table BOOK(
    ISBN VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(4000) NOT NULL,
    PRIMARY KEY (ISBN)
);
--CREATING BOOK_AUTHORS TABLE
CREATE TABLE BOOK_AUTHORS(
    AUTHOR_ID VARCHAR2(50) NOT NULL,
    ISBN VARCHAR2(50) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);
--CREATING AUTHORS TABLE
CREATE TABLE AUTHORS(
    AUTHOR_ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);
--CREATING LIBRARY_BRANCH TABLE
CREATE TABLE LIBRARY_BRANCH(
    BRANCH_ID VARCHAR2(50) NOT NULL,
    BRANCH_NAME VARCHAR2(4000) NOT NULL,
    ADDRESS VARCHAR2(4000) NOT NULL,
    PRIMARY KEY(BRANCH_ID)
);
--CREATING TABLE BOOK_COPIES
CREATE TABLE BOOK_COPIES(
    BOOK_ID VARCHAR2(50) NOT NULL,
    ISBN VARCHAR2(50) NOT NULL,
    BRANCH_ID VARCHAR2(50) NOT NULL,
    PRIMARY KEY(BOOK_ID)
);
--CREATING TABLE FOR BORROWERS
CREATE TABLE BORROWERS(
    CARD_NO VARCHAR2(50) NOT NULL,
    SSN VARCHAR2(50) NOT NULL,
    FNAME VARCHAR2(50) NOT NULL,
    LNAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(4000) NOT NULL,
    PHONE VARCHAR2(4000) NOT NULL,
    PRIMARY KEY (CARD_NO)
);
--CREATING TABLE FOR BOOK_LOANS
CREATE TABLE BOOK_LOANS(
    LOAN_ID VARCHAR2(50) NOT NULL,
    BOOK_ID VARCHAR2(50) NOT NULL,
    CARD_NO VARCHAR2(50) NOT NULL,
    DATE_OUT DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    DATE_IN DATE NOT NULL,
    PRIMARY KEY (LOAN_ID)
);
--CREATING TABLE FINES
CREATE TABLE FINES(
    LOAN_ID VARCHAR2(50) NOT NULL,
    FINE_AMT NUMBER NOT NULL,
    PAID CHAR(10) NOT NULL,
    PRIMARY KEY (LOAN_ID)
)